<a href="https://colab.research.google.com/github/Rakesh-Online/NN_From_Scratch_Numpy/blob/master/Neural_Network_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Building Neural network from scratch with numpy 

In [2]:
import numpy as np 
training_set = np.array([[0,1,0],
                         [0,0,1],
                         [1,0,0],
                         [1,1,0],
                         [1,1,1],
                         [0,1,1],
                         [0,1,0]])

labels = np.array([[1,0,0,1,1,0,1]])
labels = labels.reshape(7,1)
print(training_set)
print(labels)

[[0 1 0]
 [0 0 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]
 [0 1 1]
 [0 1 0]]
[[1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]]


In [3]:
#Hyperparameters 
np.random.seed(35)
weights = np.random.rand(3,1)
bias = np.random.rand(1)
lr = 0.05
print(weights)
print(bias)

[[0.45805495]
 [0.30834961]
 [0.23148705]]
[0.27742455]


In [4]:
#Activation function
def sigmoid(x):
  return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
  return sigmoid(x)*(1-sigmoid(x))

In [5]:
#Training
for epochs in range(3000):
  inputs = training_set
  xw = np.dot(inputs,weights)+bias
  z = sigmoid(xw)
  error = z - labels
  print(error.sum())
  dcost = error
  dpred = sigmoid_derivative(z)
  z_del = dcost *dpred
  inputs = training_set.T
  weights = weights - lr*np.dot(inputs,z_del)
  for num in z_del:
    bias = bias -lr*num 
inputs = training_set 


0.8002420070865376
0.783392194532465
0.7669173487988152
0.7508147720414474
0.7350813631145104
0.7197136468700333
0.7047078029336641
0.690059693845631
0.6757648924703729
0.661818708592112
0.648216214626784
0.6349522703931563
0.6220215468975684
0.6094185490975411
0.5971376376194024
0.5851730494141824
0.5735189173442473
0.56216928870054
0.5511181426568755
0.5403594066735602
0.5298869718676674
0.519694707371675
0.5097764737059016
0.50012613519328
0.49073757144757024
0.4816046879681526
0.47272142587611354
0.46408177082749
0.4556797611403103
0.44750949517250893
0.43956513798791486
0.43184092734741175
0.4243311790619918
0.4170302917438895
0.4099327509912719
0.4030331330410908
0.3963261079237541
0.38980644215219884
0.38346900097681513
0.3773087502364818
0.3713207578347505
0.36550019486894325
0.35984233643867436
0.3543425621590275
0.3489963564023538
0.3437993082913987
0.3387471114652474
0.3338355636383493
0.3290605659717303
0.32441812227434097
0.31990433805139873
0.3155154194155033
0.3112476718

In [6]:
#Predictions 
single_pt = np.array([1,0,0])
result = sigmoid(np.dot(single_pt,weights)+bias)
print(result)

[0.14819097]


In [7]:
#predictions
single_pt = np.array([0,1,0])
result = sigmoid(np.dot(single_pt,weights)+bias)
print(result)

[0.9284892]
