<a href="https://colab.research.google.com/github/Rakesh-Online/NN_From_Scratch_Numpy/blob/master/Neural_Network_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Building Neural network from scratch with numpy 

In [6]:
import numpy as np 
training_set = np.array([[0,1,0],
                         [0,0,1],
                         [1,0,0],
                         [1,1,0],
                         [1,1,1],
                         [0,1,1],
                         [0,1,0]])

labels = np.array([[1,0,0,1,1,0,1]])
labels = labels.reshape(7,1)
print(training_set)
print(labels)

[[0 1 0]
 [0 0 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]
 [0 1 1]
 [0 1 0]]
[[1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]]


In [9]:
#Hyperparameters 
np.random.seed(35)
weights = np.random.rand(3,1)
bias = np.random.rand(1)
lr = 0.05
print(weights)
print(bias)

[[0.45805495]
 [0.30834961]
 [0.23148705]]
[0.27742455]


In [10]:
#Activation function
def sigmoid(x):
  return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
  return sigmoid(x)*(1-sigmoid(x))

In [15]:
#Training
for epochs in range(30000):
  inputs = training_set
  xw = np.dot(inputs,weights)+bias
  z = sigmoid(xw)
  error = z - labels
  print(error.sum())
  dcost = error
  dpred = sigmoid_derivative(z)
  z_del = dcost *dpred
  inputs = training_set.T
  weights = weights - lr*np.dot(inputs,z_del)
  for num in z_del:
    bias = bias -lr*num 
inputs = training_set 


Streaming output truncated to the last 5000 lines.
-0.0026645585075156727
-0.0026644849980547655
-0.0026644114918329374
-0.0026643379888499873
-0.002664264489105894
-0.0026641909926001933
-0.002664117499333398
-0.002664044009304964
-0.0026639705225150224
-0.002663897038963515
-0.002663823558650417
-0.002663750081574996
-0.002663676607737489
-0.002663603137138735
-0.002663529669777717
-0.0026634562056546615
-0.0026633827447688774
-0.0026633092871205938
-0.0026632358327105497
-0.002663162381538107
-0.002663088933602932
-0.0026630154889046576
-0.002662942047444234
-0.0026628686092211584
-0.0026627951742348166
-0.0026627217424844904
-0.002662648313972435
-0.0026625748886968115
-0.0026625014666578142
-0.002662428047855832
-0.002662354632290618
-0.0026622812199614335
-0.0026622078108690765
-0.002662134405012527
-0.0026620610023922672
-0.00266198760300812
-0.0026619142068601623
-0.0026618408139491567
-0.0026617674242737574
-0.002661694037833312
-0.002661620654629073
-0.0026615472746607735
-0.

In [18]:
#Predictions 
single_pt = np.array([1,0,0])
result = sigmoid(np.dot(single_pt,weights)+bias)
print(result)

[0.01890607]


In [17]:
#predictions
single_pt = np.array([0,1,0])
result = sigmoid(np.dot(single_pt,weights)+bias)
print(result)

[0.98977835]
